// <auto-generated />
using Hallx.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hallx.Persistence.Migrations
{
    [DbContext(typeof(HallxDbContext))]
    [Migration("20240521063011_productclass")]
    partial class productclass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hallx.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 6,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 7,
                            Name = "Soap"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 9,
                            Name = "Hamper"
                        });
                });

            modelBuilder.Entity("Hallx.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Eric Ries",
                            Description = "How Today's Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses",
                            ISBN = "978-0307887894",
                            ListPrice = 19.989999999999998,
                            Price = 14.99,
                            Price100 = 10.99,
                            Price50 = 12.99,
                            Title = "The Lean Startup"
                        },
                        new
                        {
                            Id = 2,
                            Author = "James Clear",
                            Description = "An Easy & Proven Way to Build Good Habits & Break Bad Ones",
                            ISBN = "978-0735211292",
                            ListPrice = 17.989999999999998,
                            Price = 12.99,
                            Price100 = 9.9900000000000002,
                            Price50 = 11.99,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Matt Haig",
                            Description = "A Novel",
                            ISBN = "978-0525559474",
                            ListPrice = 21.989999999999998,
                            Price = 16.989999999999998,
                            Price100 = 12.99,
                            Price50 = 14.99,
                            Title = "The Midnight Library"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Dalai Lama XIV, Howard C. Cutler",
                            Description = "A Handbook for Living",
                            ISBN = "978-1573221801",
                            ListPrice = 15.99,
                            Price = 11.99,
                            Price100 = 8.9900000000000002,
                            Price50 = 10.99,
                            Title = "The Art of Happiness"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Paulo Coelho",
                            Description = "A Fable About Following Your Dream",
                            ISBN = "978-0061122416",
                            ListPrice = 13.99,
                            Price = 9.9900000000000002,
                            Price100 = 7.9900000000000002,
                            Price50 = 8.9900000000000002,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Suzanne Collins",
                            Description = "Book 1 of the Hunger Games Trilogy",
                            ISBN = "978-0439023481",
                            ListPrice = 12.99,
                            Price = 8.9900000000000002,
                            Price100 = 6.9900000000000002,
                            Price50 = 7.9900000000000002,
                            Title = "The Hunger Games"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Mark Manson",
                            Description = "A Counterintuitive Approach to Living a Good Life",
                            ISBN = "978-0062457714",
                            ListPrice = 18.989999999999998,
                            Price = 14.99,
                            Price100 = 11.99,
                            Price50 = 13.99,
                            Title = "The Subtle Art of Not Giving a F*ck"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Charles Duhigg",
                            Description = "Why We Do What We Do in Life and Business",
                            ISBN = "978-0812981605",
                            ListPrice = 17.989999999999998,
                            Price = 13.99,
                            Price100 = 10.99,
                            Price50 = 12.99,
                            Title = "The Power of Habit"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Andy Weir",
                            Description = "A Novel",
                            ISBN = "978-0553418026",
                            ListPrice = 15.99,
                            Price = 11.99,
                            Price100 = 9.9900000000000002,
                            Price50 = 10.99,
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Stephen R. Covey",
                            Description = "Powerful Lessons in Personal Change",
                            ISBN = "978-0671708634",
                            ListPrice = 22.989999999999998,
                            Price = 17.989999999999998,
                            Price100 = 13.99,
                            Price50 = 15.99,
                            Title = "The 7 Habits of Highly Effective People"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
